### ISSUE TITLE
Unable to Authorize Real Debrid

### ISSUE THREAD

**Issue by beatlesdbp** [nixgates/plugin.video.seren#280]
I am unable to authorize my Real Debrid Account. When in Seren, I click on Configure, Accounts, Real-Debrid, Authorize Real-Debrid. You click on it, and the screen pops up that says:

Seren:Real-Debrid Auth
open this link in a browser: (Blank)
Enter the code: (Blank)
This code has been copied to your clipboard

**Comment by nixgates** [comment]
Hey bud, can I please request a log for this issue. Thank you!

**Comment by Daviddew89** [comment]
I had a similar issue that I resolved by switching to the stock Kodi skin. I believe it's the highlight color not being selected.

**Comment by nixgates** [comment]
@beatlesdbp can you try this as a temporary workaround? 

I'll look into it now and try and find a permanent fix

**Comment by beatlesdbp** [comment]
Hello,
So I tried authenticating my real debrid account with the normal theme Estuary. it still does not work. It says it is authenticated and then immediately there is an error and when I go to play a movie it says it cannot play the movie. How soon do you think this will be able to get fixed? Thanks!
David Prospect 

 

    On Saturday, January 2, 2021, 11:28:45 PM EST, nixgates <notifications@github.com> wrote:  
 
 


@beatlesdbp can you try this as a temporary workaround?

I'll look into it now and try and find a permanent fix

**Comment by nixgates** [comment]
@beatlesdbp I'm going to need a log covering your attempt to authorize RD to fix this one up as I can't replicate it on my system. 

As soon as you get me that I'll work on it :)

**Comment by beatlesdbp** [comment]
It’s cool, I’m already using a different kodi add on but thanks anyways

Best Regards,


David Prospect
david_prospect@yahoo.com

**Comment by nixgates** [comment]
@beatlesdbp this issue is now resolved in 2.0.10 👍

**Comment by beatlesdbp** [comment]
Hey thanks for letting me know. I have now switched back to Seren!
David Prospect 

 

    On Wednesday, January 6, 2021, 02:05:14 AM EST, nixgates <notifications@github.com> wrote:  
 
 


@beatlesdbp this issue is now resolved in 2.0.10 👍

**Comment by 101ben1011** [comment]
Hi Nixgates,

Just thought I would update you.
You closed my bug report as a likely dupe of this bug.

The latest update 2.0.10 has fixed the real debrid issue, and that is now working fine, so thanks.

The trakt issue is still present, and I am unable to authorise my trakt account on the xbox as it creates an error. Works fine on my android devices though.

Just thought I'd let you know, in case you thought this would fix the trakt issue as well.

Thanks,
Ben

**Comment by nixgates** [comment]
@101ben1011 hey bud, yea sorry about closing duplicates. They just make it really hard to diagnose and keep track otherwise.

In saying that, raise a new issue for your trakt auth issue and I'll have a look for you :)
(Can you please make sure to include a log for me! Thank you!)

**Comment by 101ben1011** [comment]
Hey, no need to apologise, its no problem at all. Makes sense to close dupes, just wanted to let you know there was still a gremlin. I know you've got a lot on as it is. I will open a new issue tomorrow with a new log, then if you get time, you could take a look.

**Comment by nixgates** [comment]
@101ben1011 think there might be a relevant issue already for that one, have a quick search for me before you raise a new ticket? 

Closing this one off :)

**Comment by DoMango7** [comment]
I am unable to authorize my real debrid.  Every time I click authorize no code appears and then like 5 minutes later it randomly  appears, it seems non responsive.  Any fixes?

**Comment by DoMango7** [comment]
This has been resolved.  I had to click authorize wait several minutes for box to appear, authenticate account and wait several more minutes for box to say it was successful.  Previously I kept getting impatient and clicking the authorize and every time I would enter the code for real debrid a new one would appear therefore making the one I entered prior voided is my guess.
