### ISSUE TITLE
[BUG] Real Debrid Expired account notification

### ISSUE THREAD

**Issue by Gaddinator90** [nixgates/plugin.video.seren#314]
On the latest version of Seren, I have 49 days left on my Real Debrid subscription, Seren won't scrape any RD links and notifies me saying my account has expired, I've tried re authorising with no luck..

**Comment by WheelMan3** [comment]
Mine is still working but it’s doing this exact same thing.

**Comment by WheelMan3** [comment]
> On the latest version of Seren, I have 49 days left on my Real Debrid subscription, Seren won't scrape any RD links and notifies me saying my account has expired, I've tried re authorising with no luck..

Hey I think I found a temporary fix, if you click check for updates and then update to the most current version even if you already on their version it should still make it go from Saying expired to premium.

**Comment by Gaddinator90** [comment]
Thanks!

**Comment by nixgates** [comment]
@Gaddinator90 sounds like the issue was fixed in a previous update, would you mind confirming?

**Comment by Gaddinator90** [comment]
Have applied new update this morning and will continue to test, I'll keep you posted if you don't mind, thanks for all your hard work

**Comment by Gaddinator90** [comment]
@nixgates seems to be ok now, thank you very much I'll report if I have any issues

**Comment by knowell12** [comment]
I am having the same issue with current version (2.0.17+matrix.1). I tried updating and did not fix the issue

**Comment by hidalgo67** [comment]
Same issue with version 2.0.18+matrix.1

**Comment by Legion64bit** [comment]
May 31,2021
I somehow found the solution to RD being expired on Seren. I just tried to update the addon and there’s two available update options with the same versions 2.0.19. At first i thought they were two same updates and only chose the first one on top of the list but nothing happened. Same issue on which RD account is still expired. But when I chose the bottom version to update Seren I somehow fixed it. Went back to Seren account settings and found out RD status is back to PREMIUM.

**Comment by drinfernoo** [comment]
@Legion64bit You have two repos installed that offer it, I would assume. They should be the same version, unless one is modified somehow.

**Comment by Legion64bit** [comment]
@drinfernoo maybe i do have repos that comes with the build i installed and from the stand alone seren i added to the build. But never had issues with seren previously. I recently downgraded my kodi to 8.9 for i have noticed several issues with kodi19 version. I had to look for the solutions like expired RD account on Seren and sources restrictive issues and found this thread. Somehow I figured it out also.

**Comment by Syrah-NL** [comment]
Same here. After attempting relinking RD several times to no avail, updating Seren to the version I already had from the Nixgates repo fixed the issue.

**Comment by Syrah-NL** [comment]
> Same here. After attempting relinking RD several times to no avail, updating Seren to the version I already had from the Nixgates repo fixed the issue.

Sadly the next day the problem is back and now I can't fix it by updating (tried 5-6 times).

**Comment by SUroot** [comment]
Had the same problem on the latest build (using latest Kodi Leia) yesterday. Re-auth didn't work initially but after force closing Kodi and restarting it, I was back to premium. This lasted until today.

**Comment by Conspiracy73** [comment]
Seems this is an ongoing issue, not sure if it is isolated since someone said it happened in venom add-on as well. Forced update of same 2.1.0 and it corrected the issue.

**Comment by drinfernoo** [comment]
There's a newer issue in #619, which is based on 2.1.0.
