### ISSUE TITLE
[BUG] Playing file on Kodi 19 with RD throws JSONDecodeError 

### ISSUE THREAD

**Issue by fjen** [nixgates/plugin.video.seren#487]
**Logs**

https://paste.kodi.tv/ihuqebukev.kodi

**Describe the bug**
Trying to play a file from the sources list with RD throws a `simplejson.errors.JSONDecodeError`. Seren just skips through all sources without success. I don't know whether simplejson belongs to the default installation. It seems like the exception import is wrong if that's the case.

Fixed it by replacing the import line in `resources/lib/debrid/real_debrid.py`
```python
from json.decoder import JSONDecodeError
```
with
```python
from simplejson.errors import JSONDecodeError 
```

**To Reproduce**
1. Go to any Movie
2. Select Source

**Expected behavior**
File plays.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0rc1 (LibreELEC 9.80 on arm)
 - Version 2.0.16

**Comment by sathish804** [comment]
@fjen I tried to reproduce it on my Android device with Kodi 19rc1 and Seren 2.0.16 by selecting source but I don't see any issue and source played without any issue. Here is the log.

https://controlc.com/368d6ebf

**Comment by fjen** [comment]
This happens to me on LibreELEC on arm.

**Comment by fjen** [comment]
I have done a little more testing and tried a fresh LibreELEC X86_64 9.80 nightly build installation on a second machine. The LibreELEC build dates as well as python, simplejson, requests versions are the same on both machines. The error is not occurring on the second machine.

Anyway. LibreELEC provides simplejson and requests uses that if it's available. See:
https://github.com/psf/requests/blob/master/requests/compat.py#L29
That means the Exception import is still wrong here if simplejson is available.

Here is a full log from start to error: https://paste.kodi.tv/neyiyagamu.kodi

**Comment by kosta296** [comment]
Confirming @fjen by replacing the import line in real_debrid.py fixed source playback on Arm CoreElec Matrix.

**Comment by trkselim** [comment]
> Confirming @fjen by replacing the import line in real_debrid.py fixed source playback on Arm CoreElec Matrix.
Hi
Which line should i replace ?

**Comment by kosta296** [comment]
> > Confirming @fjen by replacing the import line in real_debrid.py fixed source playback on Arm CoreElec Matrix.
> > Hi
> > Which line should i replace ?

SMB into box.

Open Addons folder then

plugin.video.seren / Resources / lib / Debrid 

Then open real_debrid.py with Notepad and

Change the line:

from json.decoder import JSONDecodeError

with

from simplejson.errors import JSONDecodeError 

Save the change and reboot for the change to take effect.

**Comment by trkselim** [comment]
Thanks

**Comment by nixgates** [comment]
Thanks all! 

Will include this in the next update

**Comment by newf276** [comment]
> This happens to me on LibreELEC on arm.

I also was having same issue on Lbreelec Generic nightlies. Changed the file as you suggested, error now fixed, RD works fine.  Funny it worked fine with my PM account, just not with RD. Thanks for your fix.

**Comment by fjen** [comment]
The PM and AD debrid providers do not mess with JSONDecodeError, that's why everything is fine there.

I wonder why the LibreELEC Generic nightly is working for me but not for you.

**Comment by newf276** [comment]
> The PM and AD debrid providers do not mess with JSONDecodeError, that's why everything is fine there.
> 
> I wonder why the LibreELEC Generic nightly is working for me but not for you.

I am not sure. I just changes the line of cose and now it works.

**Comment by nixgates** [comment]
Fixed for next update :+1:

**Comment by newf276** [comment]
> Thanks all!
> 
> Will include this in the next update

Thank You.  Separate question for you, and you can tell me to bug off if you want.  I notice that jurialmunkey says using Trakt Collection is not the best way to go, and that we should be syncing our watchlist vice collection.  Do you think that this is better, and if so, how difficult would it be to have Seen sun watchlist vice collection, so both TMDB Helper and Seven use the same approach?  Thanks again.

**Comment by ansa70** [comment]
This fix does not work for me. The only thing that sometimes works is going into Tools and do a Clear Cache and Clear Local Torrent Cache, then it starts working again for a while. Also it looks like it's time dependent: if I try the next day Seren works again for some time without doing Clear Cache. Also I'd like to point out that even if I don't change the "from json.decoder import JSONDecodeError" line, the behaviour is the same, and the exception thrown in the logs is still from simplejson.errors.JSONDecodeError, so I doubt this is even related to the real issue

**Comment by fjen** [comment]
Of course `simplejson.errors.JSONDecodeError` appears in the log if you do not change the import line. That exception is not catched in that case which is not intended.

Your cache issue does not seem to be related.

**Comment by ansa70** [comment]
> Of course `simplejson.errors.JSONDecodeError` appears in the log if you do not change the import line. That exception is not catched in that case which is not intended.
> 
> Your cache issue does not seem to be related.

Ok my understanding of python is very limited, it's the only major language I don't know... 
I can confirm that my issue is not related at all to this one, I tried again with a clean install of Kodi 18 and Seren and still having the same issue.

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.17.
