### ISSUE TITLE
[BUG] Can't update trakt after 2.1.0 upgrade

### ISSUE THREAD

**Issue by watar** [nixgates/plugin.video.seren#618]
**Logs**
http://repo.mywire.org/tmp/kodi.log

**Describe the bug**
After updating to 2.1.0 I can't update trakt.
Tried reauthorizing trakt/RD, clear cache, torrent cache, metadata, rebuilding the database, removing and reinstalling Sren completely... but no luck.

**Expected behavior**
An updated trakt database 

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1.0
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6642114/kodi.log)

**Comment by drinfernoo** [comment]
Can you attempt to clear Seren's cache, and then rebuild your Trakt database?

In that order, with nothing in between.

**Comment by watar** [comment]
Seren - Settings - Shortcuts - Clear cache
After I pressed Ok for that a Trakt rebuild started automatically. It wen't to 100% and then disappeared, usually I get a msg saying "trakt database rebuild complete something..." No messages at all this time.

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6642355/kodi.log)

**Comment by watar** [comment]
and when I  started it manually I get the same roor msg again

**Comment by ThePapaw** [comment]
Since I updated to latest version of Seren, it runs "rebuilding Trakt sync database" every time I open the media center, then over and over like every 20-30 minutes. I'm running my own fork of Kodi v18.9 on 3 different Nvidea Shields and they are all doing it after updating Seren. I installed the genuine Kodi v18.9 and does the same thing.

Very annoying if you're watching a movie or even local channels via HD-Homerun and it pops up continuously every 20-30 minutes or so.

I have a couple things I will try later and get a log posted. Experiencing storms and power is flickering off and on currently. Just wanted to add to this a bit.

**Comment by drinfernoo** [comment]
I think we need a better log of your actual rebuild happening:

* Start Kodi and wait for at least 5 minutes
* Enable "Debug Logging" in Kodi
* Clear cache in Seren
* Rebuild Database in Seren
* Do not exit Seren menu until completed

Then send that log.

**Comment by ThePapaw** [comment]
Had a chance to do as requested, sure hope this helps.

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6643965/kodi.log)

**Comment by kaufman2000** [comment]
> Since I updated to latest version of Seren, it runs "rebuilding Trakt sync database" every time I open the media center, then over and over like every 20-30 minutes. I'm running my own fork of Kodi v18.9 on 3 different Nvidea Shields and they are all doing it after updating Seren. I installed the genuine Kodi v18.9 and does the same thing.
> 
> Very annoying if you're watching a movie or even local channels via HD-Homerun and it pops up continuously every 20-30 minutes or so.
> 
> I have a couple things I will try later and get a log posted. Experiencing storms and power is flickering off and on currently. Just wanted to add to this a bit.

I have this issue with Trakt stuck on database rebuild loop. I've tried deauthorising and reauthorising Trakt, clearing the cache etc but with no luck in fixing it.

**Comment by ThePapaw** [comment]
> I have this issue with Trakt stuck on database rebuild loop. I've tried deauthorising and reauthorising Trakt, clearing the cache etc but with no luck in fixing it.

Maybe you can follow instructions posted above by @drinfernoo, get a log posted and it might help the dev. figure it out. I am sure all the help he gets the sooner they can get a fix.

**Comment by kaufman2000** [comment]
Ok hopefully this will help, sorry if it is wrong.

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6649613/kodi.log)

**Comment by kaufman2000** [comment]
Do either myself or @ThePapaw need to create a separate issue for the Trakt database rebuild loop?

**Comment by drinfernoo** [comment]
No, it's a known issue already.

**Comment by drinfernoo** [comment]
Fixes for this should be coming in the next version.

**Comment by sammydc77** [comment]
I use Trakt 2.1.0 on Kodi 19.1 on a Google Pixelbook i5 8GB/256GB, Stable State Chrome OS.  I agree that Trakt is not auto-updating, but I just right-click on the Episode I viewed and go to the Trakt Manager and select Watched, it does update Trakt and the Checkmark is present afterwards, granted it is not a fix, just a workaround.  Additionally, after watching two-episodes, I have to restart Kodi 19.1 to continue and watch another two, just another workaround until they have time to update.  I still believe Seren is the best, and is worth the wait.  Also, on a side note, I would like to thank whoever was involved with the Kodi v19.1 fix to allow the External SSD's to be recognized [with the actual Label of the drive] again for use.

**Comment by drinfernoo** [comment]
This should now be fixed in 2.1.1.

**Comment by watar** [comment]
Works like a charm again 👍 
Thank you :)

**Comment by sammydc77** [comment]
I really appreciate all of your time with this.

Thanx!

**Comment by kaufman2000** [comment]
I'm still getting the database sync loop problem in the latest update

**Comment by ThePapaw** [comment]
I am still getting the rebuilding loop with 2.1.1

**Comment by kaufman2000** [comment]
> I am still getting the rebuilding loop with 2.1.1

I had this too with the new update. I revoked Trakt authorisation in Seren. Then cleared Serens cache and reauthorised Trakt. Seems to be erking now woth no loop.
