### ISSUE TITLE
[BUG] "No playable sources found" on everything. Even after fresh install

### ISSUE THREAD

**Issue by Pmaw10** [nixgates/plugin.video.seren#623]
**Logs**

Please provide debug logs to assist with your issue

https://pastebin.com/E0KkRWpf

**Describe the bug**
Seren begins to search for sources but quickly stops and says "No playable sources found." Even SD sources cannot be found. Even sources I have watched before using Seren can't be found.

**To Reproduce**
1. Go to an episode
2. Click on play episode
3. See error after Seren looks for sources

**Expected behavior**
Seren is usually able to find at least a few sources, never zero.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.1.0

**Comment by talondnb** [comment]
https://github.com/nixgates/plugin.video.seren/issues/619

**Comment by drinfernoo** [comment]
At first glance, this *does not* appear to be a duplicate of #619, but it'll be looked at closer in the near future.

**Comment by drinfernoo** [comment]
I see a lot of errors from `script.module.slyguy` (maybe the Disney+ add-on?) and also the Netflix add-on... could you attempt to get a full debug log using *only* Seren to reproduce this issue?

**Comment by kodiuser-xiii** [comment]
Hi,

I'm also facing the same issue with Seren. Not sure if my log file will help but here it is.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6668165/kodi.log)

**Comment by jules-71** [comment]
Seren keeps on loosing it settings, goto accounts and reactivate, it's a current issue that needs a fix. You watch somthing and you get a message "Your accont has expired" or "No playable sources found." when you click on a show to watch.

**Comment by drinfernoo** [comment]
This should be fixed with the next update.

**Comment by kodiuser-xiii** [comment]
Hi @drinfernoo, when is the next update scheduled to be rolled out?

**Comment by drinfernoo** [comment]
This should now be fixed in 2.1.1.

**Comment by maxpower742** [comment]
Hi @drinfernoo, sorry if this is an obvious question, but should it auto-update to 2.1.1? My Seren still currently says 2.1.0

**Comment by jules-71** [comment]
I have even reloaded Kodi 19 and put a fresh reload of Seren 2.1.0 latest version still does it, thought a good clear out might solve the problem with corrupt files. It's the software, a glitch in the Matrix. I only have Seren on my box. Have to wait for the new version to come out, last update was September last year.

**Comment by drinfernoo** [comment]
@maxpower742 Kodi auto-updates add-ons by default, but if you've turned that setting off, then it obviously will not do that. You are always free to update manually anyways.

@jules-71... The latest version is 2.1.1. Update Seren.

**Comment by maxpower742** [comment]
@drinfernoo thanks, it seems to have fixed itself, and it now says 2.1.1. However, i'm still having issues in connecting with RD. I'm getting the error message "failed to refresh RD token". When i try and re-authorise on my shield tv, it just stays stuck on the screen on the pop-up with the code and appears to have not gone through, but is says confirmed on my laptop via the RD device authorisation.

**Comment by deanwethers** [comment]
> @drinfernoo thanks, it seems to have fixed itself, and it now says 2.1.1. However, i'm still having issues in connecting with RD. I'm getting the error message "failed to refresh RD token". When i try and re-authorise on my shield tv, it just stays stuck on the screen on the pop-up with the code and appears to have not gone through, but is says confirmed on my laptop via the RD device authorisation. 

I am having the same issue on Nvidia shield pro too. I can't get real debrid to authorize, the popup just stays there even though the website shows it was added. But within seren itself it's still not showing any account info

**Comment by drinfernoo** [comment]
Are you able to play anything? The account information does not get immediately filled in, but should get filled in next time the token is checked.

**Comment by deanwethers** [comment]
> Are you able to play anything? The account information does not get immediately filled in, but should get filled in next time the token is checked.

I can't play anything it says no sources found playback failed. When I restart kodi it says failed to refresh RD token please manually refresh but when entering the code the popup with the code never goes away. I will try a fresh install and see if that works

**Comment by drinfernoo** [comment]
@deanwethers Ok. Please keep it in your own issue, as I've requested more information there, which you're not giving me here either.

**Comment by peno64** [comment]
I just have this also with 2.1.1. I watched 2 episodes of a series, no problem there and while watching the second episode I already got the message that no playable sources can be found for the next one and indeed it doesn't find any. Even not for the episodes I just  watched! Also after clear cache I still have this.
So tried another series I watched before (The mandalorian) which should have plenty  streams and still no streams it can find. So this seems to be for everything now.

**Comment by peno64** [comment]
After a reboot  of my kodi device (raspberry pi4) and thus a restart of kodi the streams are found again...

**Comment by peno64** [comment]
This is the log from the moment problems start to occur (so before restarting my device): https://paste.kodi.tv/xaqoqecuha.kodi

**Comment by Mrtigger84** [comment]
Same problem here, as described in #630  settings reset, streams stop working.

**Comment by peno64** [comment]
@Mrtigger84 I am not so sure this is the same problem. My settings were not lost at all. The scraper doesn't find any streams but after a restart of kodi it worked again.

**Comment by Mrtigger84** [comment]
> @Mrtigger84 I am not so sure this is the same problem. My settings were not lost at all. The scraper doesn't find any streams but after a restart of kodi it worked again.

The reason I say same issue, as all issues occur at same time. And it took a while of messing about on 2.10 but figured out that was also the same. Debrid loses authorisation, stream stops and when I then check settings after it's all reset too. I see someone else has states same thing so guessing the issues are related if not linked.

**Comment by bdkbaik** [comment]
Encounter same issue, until now the "infinite" movie source cannot be found

**Comment by drinfernoo** [comment]
@bdkbaik Do you have "Hide unaired items" enabled? If so, uncheck it. "Infinite" is considered unaired at this point.

**Comment by bdkbaik** [comment]
@drinfernoo 
Oh yeah, thanks now it's working

**Comment by drinfernoo** [comment]
I can confirm this has been fixed in dev... should be working in the next update :+1:

**Comment by drinfernoo** [comment]
https://github.com/nixgates/plugin.video.seren/issues/628

**Comment by drinfernoo** [comment]
And now we're on 2.1.3, so I'm going to close this one.
