### ISSUE TITLE
[BUG] New Seren update has broke Seren for me

### ISSUE THREAD

**Issue by lowersublobia** [nixgates/plugin.video.seren#693]
Posted to the Subreddit but figured I'd post here as well

So just updated Seren to 2.1.5 and nothing seems to be working.

Trakt is all broken and won't sync properly, also cant access any of my TV show collections

Im also getting Seren errors when trying to search for any movies or TV shows, so literally everything is broken

Operating System: Windows 10

Device: Desktop

Add-on affected: Seren

Version of Kodi: 18.9

Version of add-on: 2.1.5

Country: Canada

Any support services: Real-Debrid

Log : https://paste.kodi.tv/acewetokix

**Comment by drinfernoo** [comment]
Can you try to rebuild the Trakt database from settings?

**Comment by lowersublobia** [comment]
I have tried that, and whenever I do I get an " there were issued processing your synchronization " error.

Heres an updated log after I tried rebuilding

https://paste.kodi.tv/eziqucosas

**Comment by SirRickie** [comment]
Same here. Everything in Seren is broken, nothing works (Windows 10, Kodi 18.9)

**Comment by cbizzle14** [comment]
> Same here. Everything in Seren is broken, nothing works (Windows 10, Kodi 18.9)

Same here. No matter what category I choose in movies or TV it results in an error. 18.9 as well but on Xbox

**Comment by drinfernoo** [comment]
This should be fixed in the next update already. It looks like the version of SQLite that's bundled with Leia is different from that in Matrix, which wasn't accounted for.

This issue doesn't appear to be present in Matrix, so it may be worth updating if you can't wait for the next update.

**Comment by cbizzle14** [comment]
> This should be fixed in the next update already. It looks like the version of SQLite that's bundled with Leia is different from that in Matrix, which wasn't accounted for.
> 
> This issue doesn't appear to be present in Matrix, so it may be worth updating if you can't wait for the next update.

I love the work you guys put in. Unfortunately for Xbox matrix isn't available yet. Supposedly it's real close so I'll just have to wait for the next Seren update

**Comment by trowieuk** [comment]
> This should be fixed in the next update already. It looks like the version of SQLite that's bundled with Leia is different from that in Matrix, which wasn't accounted for.
> 
> This issue doesn't appear to be present in Matrix, so it may be worth updating if you can't wait for the next update.

I am on matrix and having the same issue. Next up/previously watched widgets pop up a seren error.
If I manually try go into seren, my shows, next up/previously watched, it's empty.

How do get logs by the way?

**Comment by drinfernoo** [comment]
@trowieuk https://kodi.wiki/view/Log_file/Easy

It's unlikely that it's the same issue if you are on Matrix, for the reason I mentioned previously.

**Comment by trowieuk** [comment]
> @trowieuk https://kodi.wiki/view/Log_file/Easy
> 
> It's unlikely that it's the same issue if you are on Matrix, for the reason I mentioned previously.

Probably right, might be trakt after refreshing skin a lot it's loading all but upcoming episodes.
Still can't rebuild though, will open an issue with logs.

**Comment by SirRickie** [comment]
I can confirm that Seren 2.1.5 is working like a charm on Kodi 19.1. I'm serene again. 👍

**Comment by Bland7** [comment]
Im having same issues as lowersublobia, running exact same spec. Win10, 18.9, RD

it’s also been a nightmare to get the Settings to ‘stick’ after a ‘Wipe Addon Data‘
Generally change 2 settings, then restart kodi, repeat..


does the new Seren update present as no longer working for 18.x Kodi?
would be great to use Seren on Leia again!!

**Comment by drinfernoo** [comment]
@Bland7 No, that's not the "presentation". Only an unfortunate bug, that we'll get a release out to fix soon.

**Comment by Bland7** [comment]
A good man Infernoo
That's why your number 1

always appreciate the hard labours and offer any assistance I can from Aus

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.6 🎉 Can anyone confirm?

**Comment by cbizzle14** [comment]
@drinfernoo can confirm on Xbox. Was available to go into most popular movies and start a movie
